#!/usr/bin/env bash
# Copyright 2021 Borting Chen <bortingchen@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Set the kernel release string you attempt to present here.
FAKE_KERNEL_RELEASE="3.10.0-1160.105.1.el7.x86_64"

# Reset in case getopts has been used previously in the shell.
OPTIND=1

# Obtain original output
OUTPUT=`/bin/uname.real $@`

# Substitute kernel release string
function sub_kerenl_release() {
    if [[ ! -z ${FAKE_KERNEL_RELEASE+x} ]]; then
        ORG_KERNEL_RELEASE=`/bin/uname.real -r`
        OUTPUT=${OUTPUT/${ORG_KERNEL_RELEASE}/${FAKE_KERNEL_RELEASE}}
    fi
}

# Substitute strings in output if options is specified
while getopts "asnrvmpio" opt; do
    case "${opt}" in
        a)
            sub_kerenl_release;;
        r)
            sub_kerenl_release;;
        *)
            ;;
    esac
done

echo ${OUTPUT}


